
resolver: nightly-2025-09-26

nix:
  enable: false

system-ghc: true

packages:
- .
# - C:\Users\tom\tools\wai\wai
# - C:\Users\tom\tools\wai\wai-websockets
# - C:\Users\tom\tools\wai\warp
# - C:\Users\tom\tools\websockets
